version: 2
project_name: easyinfra
before:
  hooks:
    - go mod tidy
builds:
  - id: easyinfra
    main: ./cmd/easyinfra
    binary: easyinfra
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{- end }}'
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  version_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
release:
  github:
    owner: guneet-xyz
    name: easyinfra
  draft: false
  prerelease: auto
